(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.CatRaceGLB=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const COMPONENTS={5120:[Int8Array,'getInt8',1],5121:[Uint8Array,'getUint8',1],5122:[Int16Array,'getInt16',2],5123:[Uint16Array,'getUint16',2],5125:[Uint32Array,'getUint32',4],5126:[Float32Array,'getFloat32',4]};
  const SIZES={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16};
  function utf8(bytes){let s='';for(let i=0;i<bytes.length;i++)s+=String.fromCharCode(bytes[i]);return decodeURIComponent(escape(s));}
  function parse(buffer,THREE){
    if(ArrayBuffer.isView(buffer))buffer=buffer.buffer.slice(buffer.byteOffset,buffer.byteOffset+buffer.byteLength);
    const dv=new DataView(buffer);if(dv.getUint32(0,true)!==0x46546c67||dv.getUint32(4,true)!==2)throw new Error('Expected GLB2');
    if(dv.getUint32(8,true)!==buffer.byteLength)throw new Error('GLB length mismatch');
    let doc,bin;for(let p=12;p<buffer.byteLength;){const size=dv.getUint32(p,true),type=dv.getUint32(p+4,true);p+=8;if(p+size>buffer.byteLength)throw new Error('Truncated GLB chunk');if(type===0x4e4f534a)doc=JSON.parse(utf8(new Uint8Array(buffer,p,size)).replace(/\u0000+$/,''));if(type===0x004e4942)bin=buffer.slice(p,p+size);p+=size;}
    if(!doc||!bin)throw new Error('GLB requires JSON and binary chunks');
    if(doc.skins?.length||doc.extensionsRequired?.length)throw new Error('Skins/required extensions are outside the cloud asset contract');
    if(doc.textures?.length||doc.images?.length)throw new Error('Texture-free vertex-color GLB required for this shared loader');
    const binary=new DataView(bin),cache=new Map();
    function accessor(index){if(cache.has(index))return cache.get(index);const a=doc.accessors[index];if(a.sparse)throw new Error('Sparse accessor unsupported');const view=doc.bufferViews[a.bufferView];if(view.buffer!==0)throw new Error('External buffers unsupported');const spec=COMPONENTS[a.componentType],size=SIZES[a.type];if(!spec||!size)throw new Error('Unsupported accessor format');const [Type,get,bytes]=spec;const arr=new Type(a.count*size),offset=(view.byteOffset||0)+(a.byteOffset||0),stride=view.byteStride||size*bytes;for(let i=0;i<a.count;i++)for(let j=0;j<size;j++)arr[i*size+j]=binary[get](offset+i*stride+j*bytes,true);const result={array:arr,size,normalized:!!a.normalized};cache.set(index,result);return result;}
    const mats=(doc.materials||[]).map(m=>{const p=m.pbrMetallicRoughness||{},factor=p.baseColorFactor||[1,1,1,1];const mat=new THREE.MeshStandardMaterial({color:new THREE.Color().setRGB(factor[0],factor[1],factor[2]),roughness:p.roughnessFactor??.9,metalness:p.metallicFactor??0,opacity:factor[3],transparent:m.alphaMode==='BLEND',alphaTest:m.alphaMode==='MASK'?(m.alphaCutoff??.5):0,side:m.doubleSided?THREE.DoubleSide:THREE.FrontSide});return mat;});
    const geometryCache=new Map();
    const nodes=(doc.nodes||[]).map((n,index)=>{const group=new THREE.Group();group.name=n.name||'Node'+index;group.userData.gltfNode=index;if(n.matrix){group.matrix.fromArray(n.matrix);group.matrix.decompose(group.position,group.quaternion,group.scale);}else{if(n.translation)group.position.fromArray(n.translation);if(n.rotation)group.quaternion.fromArray(n.rotation);if(n.scale)group.scale.fromArray(n.scale);}
      if(n.skin!==undefined)throw new Error('Skinned node unsupported');
      if(n.mesh!==undefined){const mesh=doc.meshes[n.mesh];mesh.primitives.forEach((primitive,pi)=>{if(primitive.mode!==undefined&&primitive.mode!==4)throw new Error('Triangle primitives required');if(primitive.targets)throw new Error('Morph targets unsupported');const key=n.mesh+':'+pi;let geometry=geometryCache.get(key);if(!geometry){geometry=new THREE.BufferGeometry();for(const [semantic,index]of Object.entries(primitive.attributes)){const name={POSITION:'position',NORMAL:'normal',COLOR_0:'color',TEXCOORD_0:'uv'}[semantic];if(!name)continue;const a=accessor(index);geometry.setAttribute(name,new THREE.BufferAttribute(a.array,a.size,a.normalized));}if(!geometry.attributes.position)throw new Error('POSITION required');if(primitive.indices!==undefined){const a=accessor(primitive.indices);geometry.setIndex(new THREE.BufferAttribute(a.array,1));}if(!geometry.attributes.normal)geometry.computeVertexNormals();geometry.computeBoundingSphere();geometryCache.set(key,geometry);}
        const base=mats[primitive.material]||new THREE.MeshStandardMaterial({color:0xeee4d6,roughness:.9});const material=base.clone();material.vertexColors=!!geometry.attributes.color;const part=new THREE.Mesh(geometry,material);part.name=(mesh.name||group.name)+'_primitive'+pi;group.add(part);});}return group;});
    (doc.nodes||[]).forEach((n,i)=>(n.children||[]).forEach(child=>nodes[i].add(nodes[child])));
    const root=new THREE.Group();root.name='AssetRoot';for(const i of (doc.scenes?.[doc.scene||0]?.nodes||[]))root.add(nodes[i]);
    const rest=nodes.map(n=>({position:n.position.clone(),quaternion:n.quaternion.clone(),scale:n.scale.clone()}));
    const clips={};for(const animation of doc.animations||[]){const channels=animation.channels.map(ch=>{const s=animation.samplers[ch.sampler],input=accessor(s.input).array,output=accessor(s.output).array;return {node:ch.target.node,path:ch.target.path,input,output,interpolation:s.interpolation||'LINEAR',size:ch.target.path==='rotation'?4:3};});clips[(animation.name||'animation').toLowerCase()]={channels,duration:Math.max(0,...channels.map(c=>c.input[c.input.length-1]))};}
    function reset(){nodes.forEach((node,i)=>{node.position.copy(rest[i].position);node.quaternion.copy(rest[i].quaternion);node.scale.copy(rest[i].scale);});}
    function pose(name,time,loop=true){reset();const clip=clips[name];if(!clip)return false;const t=loop&&clip.duration?((time%clip.duration)+clip.duration)%clip.duration:Math.max(0,Math.min(clip.duration,time));for(const ch of clip.channels){if(!['translation','rotation','scale'].includes(ch.path))throw new Error('Unsupported animation path');let k=0;while(k<ch.input.length-2&&ch.input[k+1]<t)k++;const next=Math.min(k+1,ch.input.length-1),dt=ch.input[next]-ch.input[k],alpha=dt>0?Math.max(0,Math.min(1,(t-ch.input[k])/dt)):0;const values=[];for(let j=0;j<ch.size;j++){if(ch.interpolation==='CUBICSPLINE'){const a=ch.output[(k*3+1)*ch.size+j],b=ch.output[(next*3+1)*ch.size+j],ta=ch.output[(k*3+2)*ch.size+j],tb=ch.output[(next*3)*ch.size+j],s=alpha;values[j]=(2*s*s*s-3*s*s+1)*a+(s*s*s-2*s*s+s)*dt*ta+(-2*s*s*s+3*s*s)*b+(s*s*s-s*s)*dt*tb;}else values[j]=ch.output[k*ch.size+j]+(ch.interpolation==='STEP'?0:alpha)*(ch.output[next*ch.size+j]-ch.output[k*ch.size+j]);}
        const node=nodes[ch.node];if(ch.path==='rotation'){if(ch.interpolation==='LINEAR'){const qa=new THREE.Quaternion().fromArray(ch.output,k*4),qb=new THREE.Quaternion().fromArray(ch.output,next*4);node.quaternion.copy(qa).slerp(qb,alpha);}else node.quaternion.fromArray(values).normalize();}else node[ch.path==='translation'?'position':'scale'].fromArray(values);
      }return true;}
    return {root,nodes,clips,rest,reset,pose,stats:{triangles:[...geometryCache.values()].reduce((s,g)=>s+(g.index?g.index.count:g.attributes.position.count)/3,0),meshes:root.children.length}};
  }
  return {parse};
});
